backend: tensorflow

dataset:
  schema: delphes
  target_particles: gen
  num_input_features: 12
  num_output_features: 7
  num_input_classes: 3
  num_output_classes: 6
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  momentum_loss_coef: 1.0
  charge_loss_coef: 1.0
  pt_loss_coef: 1.0
  eta_loss_coef: 1.0
  sin_phi_loss_coef: 1.0
  cos_phi_loss_coef: 1.0
  energy_loss_coef: 0.001
  raw_path: data/pythia8_ttbar/*.pkl.bz2
  processed_path: data/pythia8_ttbar/tfr/*.tfrecords
  num_files_per_chunk: 5
  validation_file_path: data/pythia8_ttbar/val/*.pkl.bz2

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-6
  batch_size: 5
  num_events_train: 5
  num_events_test: 5
  num_epochs: 1
  num_val_files: 1
  dtype: float32
  trainable: all
  classification_loss_type: categorical_cross_entropy
  lr_schedule: exponentialdecay  # exponentialdecay, onecycle

sample_weights:
  cls: none
  charge: none
  pt: none
  eta: none
  sin_phi: none
  cos_phi: none
  energy: none
  
parameters:
  model: gnn
  bin_size: 64
  num_convs_id: 1
  num_convs_reg: 1
  num_hidden_id_enc: 1
  num_hidden_id_dec: 0
  num_hidden_reg_enc: 1
  num_hidden_reg_dec: 0
  num_neighbors: 16 
  hidden_dim_id: 64
  hidden_dim_reg: 64
  distance_dim: 64
  dropout: 0.0
  dist_mult: 1.0
  activation: elu
  skip_connection: True

timing:
  num_ev: 1
  num_iter: 1

exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes
