backend: tensorflow

dataset:
  schema: cms
  target_particles: cand
  num_input_features: 15
  num_output_features: 7
  num_input_classes: 12
  #(none, ch.had, n.had, hfem, hfhad, gamma, e, mu)
  num_output_classes: 8
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  momentum_loss_coef: 1.0
  charge_loss_coef: 1.0
  pt_loss_coef: 1.0
  eta_loss_coef: 1.0
  sin_phi_loss_coef: 1.0
  cos_phi_loss_coef: 1.0
  energy_loss_coef: 0.001
  raw_path: data/TTbar_14TeV_TuneCUETP8M1_cfi/raw/*.pkl
  processed_path: data/TTbar_14TeV_TuneCUETP8M1_cfi/tfr/*.tfrecords
  num_files_per_chunk: 5
  validation_file_path: data/TTbar_14TeV_TuneCUETP8M1_cfi/val/*.pkl

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-6
  batch_size: 5
  num_events_train: 5
  num_events_test: 5
  num_epochs: 1
  num_val_files: 1
  dtype: float32
  trainable: all
  classification_loss_type: categorical_cross_entropy
  lr_schedule: exponentialdecay  # exponentialdecay, onecycle

sample_weights:
  cls: none
  charge: signal_only
  pt: signal_only
  eta: signal_only
  sin_phi: signal_only
  cos_phi: signal_only
  energy: signal_only

parameters:
  model: gnn_dense
  activation: elu
  layernorm: no
  hidden_dim: 128
  bin_size: 320
  clip_value_low: 0.0
  num_conv: 1
  num_gsl: 1
  normalize_degrees: yes
  distance_dim: 128
  dropout: 0.0
  separate_momentum: yes
  input_encoding: cms
  debug: no

timing:
  num_ev: 1
  num_iter: 1

exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes
